# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=254)),
                ('state', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
